// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimReplenisher.DataManager;

#nullable disable

namespace SimReplenisher.DataManager.Migrations
{
    [DbContext(typeof(SimDbContext))]
    [Migration("20260125155143_ReplenishmentTable")]
    partial class ReplenishmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SimReplenisher.Domain.Entities.SimData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("SimDatas");
                });

            modelBuilder.Entity("SimReplenisher.Domain.Entities.SimToReplenish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Bank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Provider")
                        .HasColumnType("int");

                    b.Property<int>("SimDataId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SimDataId");

                    b.ToTable("ReplenishmentRequests");
                });

            modelBuilder.Entity("SimReplenisher.Domain.Entities.SimToReplenish", b =>
                {
                    b.HasOne("SimReplenisher.Domain.Entities.SimData", "SimData")
                        .WithMany()
                        .HasForeignKey("SimDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimData");
                });
#pragma warning restore 612, 618
        }
    }
}
